# Built with Jekyll 3.2.0
#
# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink: none

# Set encoding to UTF-8
encoding: utf-8
timezone: Europe/Madrid

# Markdown specs
markdown: kramdown
highlighter: rouge

collections:
  texts:
    output: true

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  footnote_backlink: "&#x21a9;&#xfe0e;"
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Setup
title:               Jolouster
tagline:             'Come, bebe y ve el bien por todo tu duro trabajo'
description:         'Hola, soy <b>Jonathan López</b> y esta es mi página personal. Aquí encontrarás mis apuntes de programación, informática e investigaciones. Devuelvo así el favor a todos aquellos que han compartido con todos su saber a través de Internet.'
url:                 'http://jolouster.com'
baseurl:             ''

# About/contact
author:
  name:              Jonathan López
  url:               https://twitter.com/jolouster
  email:             jolouster@gmail.com

# Custom vars
version:             0.0.5

# Filtrado de contenido
show_drafts: null
future: false

# Configuración
incremental: true

# Añadir feed RSS al blog
gems:
  - jekyll-feed

# Exclude optional folder
exclude: [
    .git,
    .gitignore,
    .travis.yml,
    CNAME,
    README.md,
    LICENSE.md,
    documentation.md,
    Gemfile,
    Gemfile.lock,
    optional
]


